openapi: 3.0.0
info:

  title: "argo-rollouts2"
  x-cortex-tag: "argo-rollouts"
  x-cortex-type: service
  description: |
    Please put a description here.
  x-cortex-git:
    github:
      repository: "ROKT/test-repo"
  x-cortex-owners:
    - type: group
      name: "sre"
      provider: CORTEX

  # this is effectively a list of tags used to filter services in the UI
  # currently our only use-case is for filtering services by primary language
  x-cortex-groups:
    - "Go"

  # each service should have an OpsGenie schedule
  x-cortex-oncall:
    opsgenie:
      type: SCHEDULE
      id: "SRE_schedule"

  x-cortex-link:
    - name: "argo-calendar"
      type: buildkite
      url: https://buildkite.com/rokt/argo-calendar
    - name: "argo"
      type: buildkite
      url: https://buildkite.com/rokt/argo

  # additional links may be included here
  # there's no need to link content the root folder's `./docs` as it gets picked up automatically
  # consider including resources such as DD dashboards where possible
  #  - name: RTS Dashboard
  #    type: dashboard
  #    url: https://rokt.datadoghq.com/dashboard/ax6-s8t-6dx/release-tracking-services?from_ts=1666560110637&to_ts=1666574510637&live=true